config/routes.rb
Continuity::Application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :sites do
    resources :user_groups
    resources :locations
  end
  
  resources :clinical_teams do
    resources :positions
  end

  resources :users do
    resource :contact, only: [:show, :edit, :update] do #TODO: implement as concern in Rails 4
      resources :addresses, except: [:index, :show]
      resources :phones, except: [:index, :show]
    end
    member do
      get 'login_record'
      get 'job_description'
    end
  end

  resources :patients do
    resources :visits do
      resources :notes, except: :index
    end
    resources :notes, only: :index
    resource :contact, only: [:show, :edit, :update] do #TODO: implement as concern in Rails 4
      resources :addresses, except: [:index, :show]
      resources :phones, except: [:index, :show]
    end
    collection do
      get 'search'
    end
  end
  
  match 'home' => 'home#index', as: :home
  match '/home/suggestion' => 'home#suggestion'
  match '/home/show_more' => 'home#show_more'
  match 'stats' => 'home#stats', as: :stats

  root to: 'home#public'
end

app/models/note.rb
class Note
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::Timestamps::Updated
  include Tire::Model::Search
  include Tire::Model::Callbacks

  field :user_id, type: Moped::BSON::ObjectId
  field :text, type: String
  
  belongs_to :visit
  
  validates_presence_of :user_id

  def to_indexed_json
    {
        :id => self.id,
        :text => self.text,
        :user_id => self.user_id,
        :visit_id => self.visit_id
    }.to_json
  end

  def patient_name
    self.visit.patient.name
  end

  def author
    @user = User.find(self.user_id)
    return @user.name
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  layout 'patient_chart', only: [:index, :show]
  load_and_authorize_resource :patient
  load_and_authorize_resource :visit, except: :index
  load_and_authorize_resource :note, through: :visit, except: :index
  
  # GET /patients/1/notes
  # GET /patients/1/notes.json
  def index    
    if params[:visit_id].nil?
      @visit = @patient.current_visit
      if @visit.nil?
        @visit = @patient.visits.last
      end
    else
      @visit = Visit.find(params[:visit_id])
    end
    
    @notes = @visit.notes.accessible_by(current_ability) unless @visit.nil?
      
    authorize! :index, Note
      
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /patients/1/visits/1/notes/1
  # GET /patients/1/visits/1/notes/1.json
  def show
    @author = User.find(@note.user_id) unless @note.user_id.nil?
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /patients/1/visits/1/notes/new
  # GET /patients/1/visits/1/notes/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /patients/1/visits/1/notes/1/edit
  def edit
  end

  # POST /patients/1/visits/1/notes
  # POST /patients/1/visits/1/notes.json
  def create
    @note.user_id = current_user._id
    respond_to do |format|
      if @note.save
        format.html { redirect_to patient_notes_path(@patient), notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1/visits/1/notes/1
  # PUT /patients/1/visits/1/notes/1.json
  def update
    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to patient_notes_path(@patient), notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1/visits/1/notes/1
  # DELETE /patients/1/visits/1/notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to patient_notes_path(@patient) }
      format.json { head :no_content }
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= simple_form_for [@patient, @visit, @note] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
		<%= f.input :text, as: :text, label: false, input_html: { class: 'span8' }, autofocus: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
		<%= link_to 'Cancel', patient_notes_path(@patient), class: 'btn'  %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<li class="span9">
	<div class="thumbnail">
		<%= simple_format note.text %>
		<%= link_to 'Details', patient_visit_note_path(@patient, @visit, note), class: 'btn btn-mini' %>
		<%= link_to 'Edit', edit_patient_visit_note_path(@patient, @visit, note), class: 'btn btn-mini' %>
		<%= link_to 'Delete', patient_visit_note_path(@patient, @visit, note), confirm: 'Are you sure?', method: :delete, class: 'btn btn-danger btn-mini' %>
		<em class="pull-right"><%= User.find(note.user_id).name %></em>
	</div>
</li>

app/views/notes/edit.html.erb
<div class="page-header">
<h1>Editing note</h1>
</div>

<%= render 'form' %>

app/views/notes/index.html.erb
<% content_for :sidebar do %>
<ul class="nav nav-tabs nav-stacked">
	<% @patient.visits.each do |other_visit| %>
	<% if other_visit == @visit %>
	<li class="active">
	<% else%>
	<li>
	<% end %>
		<%= link_to other_visit.name, patient_notes_path(@patient, visit_id: other_visit._id) %>
	</li>
	<% end %>
</ul>
<% end unless @visit.nil? %>

<div class="notes">
  <ul class="thumbnails">
  	<%= render @notes unless @notes.nil? %>
  </ul>
</div>

<% if @visit.present? %>
<div class="form-actions">
<%= link_to 'New Note', new_patient_visit_note_path(@patient, @visit), class: "btn btn-primary" %>
</div>
<% else %>
No notes, create a new visit first.
<% end %>

app/views/notes/new.html.erb
<div class="page-header">
<h1>New note</h1>
</div>

<%= render 'form' %>

app/views/notes/show.html.erb
<p><%= simple_format @note.text %></p>
<strong>By: </strong>
<%= @author.name %>

<div class="form-actions">
<%= link_to 'Edit', edit_patient_visit_note_path(@patient, @visit, @note), class: 'btn' %> 
<%= link_to 'Back', patient_notes_path(@patient), class: 'btn' %>
<%= link_to 'Delete', patient_visit_note_path(@patient, @visit, @note), confirm: 'Are you sure?', method: :delete, class: 'btn btn-danger pull-right' %>
</div>