config/routes.rb
Continuity::Application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :sites do
    resources :user_groups
    resources :locations
  end
  
  resources :clinical_teams do
    resources :positions
  end

  resources :users do
    resource :contact, only: [:show, :edit, :update] do #TODO: implement as concern in Rails 4
      resources :addresses, except: [:index, :show]
      resources :phones, except: [:index, :show]
    end
    member do
      get 'login_record'
      get 'job_description'
    end
  end

  resources :patients do
    resources :visits do
      resources :notes, except: :index
    end
    resources :notes, only: :index
    resource :contact, only: [:show, :edit, :update] do #TODO: implement as concern in Rails 4
      resources :addresses, except: [:index, :show]
      resources :phones, except: [:index, :show]
    end
    collection do
      get 'search'
    end
  end
  
  match 'home' => 'home#index', as: :home
  match '/home/suggestion' => 'home#suggestion'
  match '/home/show_more' => 'home#show_more'
  match 'stats' => 'home#stats', as: :stats

  root to: 'home#public'
end

app/models/visit.rb
class Visit
  include Mongoid::Document
  include ActionView::Helpers::DateHelper

  field :admission_time, type: DateTime
  field :discharge_time, type: DateTime
  field :discharge_type, type: Symbol
  field :discharge_destination, type: String
  field :sensitive, type: Boolean, default: false
  
  belongs_to :patient
  belongs_to :location
  belongs_to :clinical_team
  has_many :notes
  
  validates_presence_of :patient, :location, :admission_time
  
  scope :active, where(discharge_time: nil)

  def length_of_stay
    if admission_time.present?
      return distance_of_time_in_words(admission_time, discharge_time || DateTime.now.to_date)
    else
      return "?"
    end
  end
  
  def active?
    discharge_time.nil?
  end
  
  def name
    if clinical_team.present?
      specialty = clinical_team.id.to_s
    else
      specialty = location.department
    end
    specialty + " (" + location.site.abbreviation + ") " + (I18n.l admission_time, format: :date_only)
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  layout 'patient_chart', only: [:index, :show]
  load_resource :patient
  load_and_authorize_resource :visit, through: :patient
  
  # GET /patients/1/visits
  # GET /patients/1/visits.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visits }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create    
    respond_to do |format|
      if @visit.save
        format.html { redirect_to [@patient, @visit], notice: 'Visit was successfully created.' }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to [@patient, @visit], notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to patient_visits_url(@patient) }
      format.json { head :no_content }
    end
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= simple_form_for [@patient, @visit], html: { class: 'form-horizontal' } do |f| %>
  <%= f.input :admission_time, as: :datechooser %>
  <%= f.input :discharge_time, as: :datechooser %>
  <%= f.association :location, collection: current_user.site.locations, include_blank: false,  input_html: { class: 'multiselect', style: 'width: 25em;' } %>
  <%= f.association :clinical_team, collection: current_user.site.clinical_teams, input_html: { class: 'multiselect', style: 'width: 25em;' } %>
  <%= f.input :sensitive, as: :radio_buttons, hint: 'Sensitive visits are hidden from users at other sites.' %>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
      patient_visits_path(@patient), :class => 'btn' %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<div class="page-header">
<h1>Editing visit</h1>
</div>

<%= render 'form' %>

app/views/visits/index.html.erb
<table class="table table-striped sortable">
	<thead>
		<tr>
			<th>Site</th>
			<th>Location</th>
      <th>Team</th>
			<th>Admitted</th>
			<th>Discharged</th>
			<th>Length of stay</th>
			<th>Actions</th>
		</tr>
	</thead>
  
	<% @visits.each do |visit| %>
	<tr>
		<td><%= visit.location.site.name %></td>
		<td><%= visit.location.name %></td>
    <td><%= visit.clinical_team.name unless visit.clinical_team.nil? %></td>
		<td><%= l visit.admission_time, format: :date_only  %></td>
		<td><%= visit.discharge_time.present? ? (l visit.discharge_time, format: :date_only) : 'active' %></td>
		<td><%= visit.length_of_stay %></td>
		<td>
			<%= link_to 'Show', [@patient, visit], class: 'btn btn-mini'%>
			<%= link_to 'Edit', edit_patient_visit_path(@patient, visit), class: 'btn btn-mini' %>
			<%= link_to 'Destroy', [@patient, visit], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
		</td>
	</tr>
	<% end %>
</table>

<% if can? :create, Visit %>
<div class="form-actions">
<%= link_to 'New Visit', new_patient_visit_path(@patient), class: 'btn btn-primary' %>
</div>
<% end %>

app/views/visits/new.html.erb
<div class="page-header">
<h1>New visit</h1>
</div>

<%= render 'form' %>

app/views/visits/show.html.erb
<dl class="dl-horizontal">
	<dt>Site</dt>
	<dd><%= @visit.location.site.name %></dd>
	<dt>Location</dt>
	<dd><%= @visit.location.name %></dd>
  <dt>Clinical team:</dt>
  <dd><%= @visit.clinical_team.name unless @visit.clinical_team.nil? %></dd>
</dl>

<div class="form-actions">
<%= link_to 'Edit', edit_patient_visit_path(@patient, @visit), class: 'btn' %>
<%= link_to 'Back', patient_visits_path(@patient), class:'btn' %>
</div>