config/routes.rb
Continuity::Application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :sites do
    resources :user_groups
    resources :locations
  end
  
  resources :clinical_teams do
    resources :positions
  end

  resources :users do
    resource :contact, only: [:show, :edit, :update] do #TODO: implement as concern in Rails 4
      resources :addresses, except: [:index, :show]
      resources :phones, except: [:index, :show]
    end
    member do
      get 'login_record'
      get 'job_description'
    end
  end

  resources :patients do
    resources :visits do
      resources :notes, except: :index
    end
    resources :notes, only: :index
    resource :contact, only: [:show, :edit, :update] do #TODO: implement as concern in Rails 4
      resources :addresses, except: [:index, :show]
      resources :phones, except: [:index, :show]
    end
    collection do
      get 'search'
    end
  end
  
  match 'home' => 'home#index', as: :home
  match '/home/suggestion' => 'home#suggestion'
  match '/home/show_more' => 'home#show_more'
  match 'stats' => 'home#stats', as: :stats

  root to: 'home#public'
end

app/views/shared/_partients_result.html.erb
<% if !@patients_search.blank? %>
    <% if !@patients_search.results.blank? %>

        <div class="patient-content">
        <% @patients_search.results.each do |patient| %>

            <ul class="nav nav-tabs" id="patient-tab">
              <li ><a href="#summary" data-toggle="pill"><%= icon("stethoscope") %> Summary</a></li>
              <li >
                <a href="#observations" data-toggle="pill"><%= icon("eye-open") %> Observations</a></li>
              <li class="note-tab"><a href="#notes<%= patient.id %>" data-toggle="pill"><%= icon("edit") %> Notes</a></li>
              <li >
                <a href="#prescriptions" data-toggle="pill"><%= icon("heart") %> Prescriptions</a></li>
              <li><a href="#results<%= patient.id %>" data-toggle="pill"><%= icon("beaker") %> Results</a></li>
              <li class="active">
                <a href="#demographics<%= patient.id %>" data-toggle="pill"><%= icon("user") %> Demographics</a></li>
              <li >
                <a href="<%= patient_contact_path(patient) %>" data-toggle="pill"><%= icon("phone") %> Contacts</a></li>
              <li><a href="#visits<%= patient.id %>" data-toggle="pill"><%= icon("globe") %> Visits</a></li>
            </ul>
            <div class="tab-content">
              <div id="demographics<%= patient.id %>" class="tab-pane active">
                <div class="demographic">
                  <dl class="dl-horizontal">
                    <dt>Name:</dt>
                    <dd><%= patient.name %></dd>
                    <dt>Date of Birth:</dt>
                    <dd><%= l patient.date_of_birth %></dd>
                    <dt>Gender:</dt>
                    <dd><%= patient.gender %></dd>
                  </dl>

                  <div class="form-actions">
                    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                                edit_patient_path(patient), :class => 'btn' if can? :edit, patient %>
                  </div>
                </div>
              </div>
              <div id="visits<%= patient.id %>" class="tab-pane">
                <table class="table table-striped sortable">
                  <thead>
                  <tr>
                    <th>Site</th>
                    <th>Location</th>
                    <th>Team</th>
                    <th>Admitted</th>
                    <th>Discharged</th>
                    <th>Length of stay</th>
                    <th>Actions</th>
                  </tr>
                  </thead>

                  <% patient.visits.each do |visit| %>
                      <tr>
                        <td><%= visit.location.site.name %></td>
                        <td><%= visit.location.name %></td>
                        <td><%= visit.clinical_team.name unless visit.clinical_team.nil? %></td>
                        <td><%= l visit.admission_time, format: :date_only %></td>
                        <td><%= visit.discharge_time.present? ? (l visit.discharge_time, format: :date_only) : 'active' %></td>
                        <td><%= visit.length_of_stay %></td>
                        <td>
                          <%= link_to 'Show', [patient, visit], class: 'btn btn-mini' %>
                          <%= link_to 'Edit', edit_patient_visit_path(patient, visit), class: 'btn btn-mini' %>
                          <%= link_to 'Destroy', [patient, visit], method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-mini btn-danger' %>
                        </td>
                      </tr>
                  <% end %>
                </table>
              </div>
              <div id="notes<%= patient.id %>" class="tab-pane">
                <div class="row">
                  <div class="visit-name span3">
                    <ul class="nav nav-tabs nav-stacked">
                      <% patient.visits.each do |visit| %>
                          <% if visit == patient.visits.last %>
                              <li class="active">
                          <% else %>
                              <li>
                          <% end %>
                          <a href="#<%= visit.id %>" data-toggle="pill"><%= visit.name %> </a>
                          </li>
                      <% end %>
                    </ul>
                  </div>
                  <div class="note-content span6 tab-content">
                    <% patient.visits.each do |visit| %>
                        <% if visit == patient.visits.last %>
                            <div id="<%= visit._id %>" class="tab-pane active">
                        <% else %>
                            <div id="<%= visit._id %>" class="tab-pane">
                        <% end %>
                        <% visit.notes.each do |note| %>

                            <ul class="thumbnails">
                              <li class="span6">
                                <div class="thumbnail">
                                  <p><%= simple_format note.text %></p>


                                  <%= link_to 'Edit', edit_patient_visit_note_path(patient, visit, note), class: 'btn btn-mini' %>
                                  <%= link_to 'Back', patient_notes_path(patient), class: 'btn btn-mini' %>
                                  <%= link_to 'Delete', patient_visit_note_path(patient, visit, note), confirm: 'Are you sure?', method: :delete, class: 'btn btn-danger btn-mini' %>
                                  <em class="pull-right">
                                    <strong>By: </strong>
                                    <%= note.author %>
                                  </em>
                                </div>
                              </li>
                            </ul>

                        <% end %>
                        </div>

                    <% end %>




                  </div>
                </div>
              </div>
            </div>
        <% end %>

        </div>

    <% end %>
<% end %>

<% if !@notes_search.blank? %>
    <% if !@notes_search.results.blank? %>
        <table class="table table-striped sortable tablesorter" xmlns="http://www.w3.org/1999/html">

          <thead>
          <tr class="tablesorter-header">
            <th data-column="0" class="tablesorter-header">
              <div class="tablesorter-header-inner">Site name</div>
            </th>
            <th data-column="1" class="tablesorter-header">
              <div class="tablesorter-header-inner">Patient name</div>
            </th>
            <th data-column="2" class="tablesorter-header">
              <div class="tablesorter-header-inner">Note</div>
            </th>
          </tr>
          </thead>
          <tbody>
          <tr>

            <% @notes_search.results.each do |note| %>
                <td><%= @site.name %></td>
                <td><%= note.patient_name %></td>
                <td><%= note.text %></td>

                </tr>
            <% end %>

            </tbody>
        </table>

    <% end %>
<% end %>

<div>
  <button class="btn show-more">Show more</button>
</div>