config/routes.rb
Continuity::Application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  resources :sites do
    resources :user_groups
    resources :locations
  end
  
  resources :clinical_teams do
    resources :positions
  end

  resources :users do
    resource :contact, only: [:show, :edit, :update] do #TODO: implement as concern in Rails 4
      resources :addresses, except: [:index, :show]
      resources :phones, except: [:index, :show]
    end
    member do
      get 'login_record'
      get 'job_description'
    end
  end

  resources :patients do
    resources :visits do
      resources :notes, except: :index
    end
    resources :notes, only: :index
    resource :contact, only: [:show, :edit, :update] do #TODO: implement as concern in Rails 4
      resources :addresses, except: [:index, :show]
      resources :phones, except: [:index, :show]
    end
    collection do
      get 'search'
    end
  end
  
  match 'home' => 'home#index', as: :home
  match '/home/suggestion' => 'home#suggestion'
  match '/home/show_more' => 'home#show_more'
  match 'stats' => 'home#stats', as: :stats

  root to: 'home#public'
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>

			<% if current_user.present? %>
			<a class="brand" href="<%= home_path %>"><%= current_user.site.name %></a>
			<% end %>

			<div class="nav-collapse">
				<ul class="nav">
					<% if can? :manage, Site %>
					<li id="sites"><%= link_icon "Sites", sites_path, "hospital" %></li>
					<% end %>
					<% if can? :manage, User %>
					<li id="users"><%= link_icon "Users", users_path, "user-md" %></li>
					<% end %>
					<% if can? :read, Patient %>
					<li id="patients"><%= link_icon "Patients", patients_path, "group" %></li>
					<% end %>
				</ul>
				<form class="navbar-search pull-right">
					<input type="text" class="search-query span2" placeholder="Search...">
				</form> 
				<% if current_user.present? %>
				<ul class="nav pull-right">
          <li class="divider-vertical"></li>
					<li><%= link_icon current_user.name, user_path(current_user), "cogs", 1 %></li>
					<li><%= link_icon "", destroy_user_session_path, "signout", 1, method: :delete %></li>
				</ul>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<%= render template: 'layouts/headers' %>
<body data-controller="<%= controller_name %>" data-action="<%= action_name %>">
<div class="container">
  <%= render "layouts/navbar" %>

  <% if notice %>
      <div class="alert alert-success">
        <%= icon("ok-sign", 2) %>
        <button class="close" data-dismiss="alert">×</button>
        <%= notice %>
      </div>
  <% end %>
  <% if alert %>
      <div class="alert alert-warning">
        <%= icon("warning-sign", 2) %>
        <button class="close" data-dismiss="alert">×</button>
        <%= alert %>
      </div>
  <% end %>
  <div class="content">
    <% if content_for?(:page_header) %>
        <div class="row">
          <div class="span12">
            <%= yield :page_header %>
          </div>
        </div>
    <% end %>
    <% if content_for?(:nav_menu) %>
        <div class="row">
          <div class="span12">
            <%= yield :nav_menu %>
          </div>
        </div>
    <% end %>
    <div class="row">
      <% if content_for?(:sidebar) %>
          <div class="span3">
            <%= yield :sidebar %>
          </div>
          <div class="span9">
            <%= yield %>
          </div>
      <% else %>
          <div class="span12">
            <%= yield %>
          </div>
      <% end %>
    </div>
    <!--/row-->
  </div>
  <!--/content-->
</div>
<!-- /container -->
</body>
</html>

app/views/layouts/headers.html.erb
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><%= content_for?(:title) ? yield(:title) : "Continuity" %></title>
	<%= csrf_meta_tags %>

	<!-- HTML5 shim, for IE6-8 support of HTML elements -->
	<!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
		<![endif]-->

	<%= stylesheet_link_tag "application", :media => "all" %>

	<!-- For third-generation iPad with high-resolution Retina display: -->
	<!-- Size should be 144 x 144 pixels -->
	<%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

	<!-- For iPhone with high-resolution Retina display: -->
	<!-- Size should be 114 x 114 pixels -->
	<%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

	<!-- For first- and second-generation iPad: -->
	<!-- Size should be 72 x 72 pixels -->
	<%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

	<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
	<!-- Size should be 57 x 57 pixels -->
	<%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

	<!-- For all other devices -->
	<!-- Size should be 32 x 32 pixels -->
	<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  
  <!-- Note we are using Turbolinks so scripts need to be in head: -->

  <%= javascript_include_tag "application" %>
</head>

app/views/layouts/home_chart.html.erb
<% content_for :page_header do %>
<div class="page-header">
  <h1><%= @site.name %>&emsp;<small>Welcome, <%= current_user.name %></small></h1>
</div>
<% end %>
<% content_for :sidebar do %>
<ul class="nav nav-pills nav-stacked">
	<li id="home"><%= link_icon 'Home', home_path, 'home' %></li>
  <li id="clinical_teams"><%= link_icon 'Clinical teams', clinical_teams_path, 'medkit' %></li>
  <li id="stats"><%= link_icon 'Statistics', stats_path, 'signal' %></li>
  <% if can? :read, @site %>
    <li id="sites"><%= link_icon 'Site settings', site_path(@site), 'hospital' %></li>
  <% end %>
  <li id="reference"><%= link_icon 'Useful references', 'http://www.google.com', 'book' %></li>
</ul>
<% end %>

<%= render template: 'layouts/application' %>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render template: 'layouts/headers'%>
  <body>
    <div class="container">
      <div class="content">
        <div class="row">
						<div class="span4 offset4">
							<% if notice %>
								<div class="alert alert-success"><%= notice %></div>
							<% end %>
							<% if alert %>
								<div class="alert alert-error"><%= alert %></div>
							<% end %>
						</div>
					</div>
					<div class="row">
           <div class="span4 offset4 well">
						 <h1>Continuity</h1>
						 <br/>
								<%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

    </div> <!-- /container -->
  </body>
</html>

app/views/layouts/patient_chart.html.erb
<% content_for :page_header do %>
<div class="patient-header">
	<div class="row">
		<div class= "span4">
			<h2><%= @patient.name %></h2>
		</div>
		<div class="span4">
			<h2><%= @patient.age %>&nbsp;<%= @patient.gender_symbol %>&nbsp;<small><%=l @patient.date_of_birth %></small></h2>
		</div>
		<div class="span4">
			<h2>80-837-836</h2>
		</div>
	</div>
	<% if @patient.current_visit.present? %>
	<div class="row">
		<div class="span4">
			<h4>
				<%= @patient.current_visit.location.site.abbreviation %>&nbsp;<%= @patient.current_visit.location.department %>&nbsp;
				<small><%= @patient.current_visit.length_of_stay %></small>
			</h4>
		</div>
		<div class="span4">
			<h4><%= icon "user-md" %> <%= @patient.current_visit.clinical_team.present? ? @patient.current_visit.clinical_team.name : "No consultant" %></h4>
		</div>
		<div class="span4">
			<h4><%= icon "map-marker" %> <%= @patient.current_visit.location.name %></h4>
		</div>
	</div>
</div>
	<% end %>
<% end %>
<% content_for :nav_menu do %>
	<ul class="nav nav-tabs">
		<li id="summary"><a href="#summary" data-toggle="pill"><%= icon("stethoscope") %> Summary</a></li>
		<li id="observations"><a href="#observations" data-toggle="pill"><%= icon("eye-open") %> Observations</a></li>
		<li id="notes"><a href="<%= patient_notes_path(@patient) %>"><%= icon("edit") %> Notes</a></li>
		<li id="prescriptions"><a href="#prescriptions" data-toggle="pill"><%= icon("heart") %> Prescriptions</a></li>
		<li id="results"><a href="#results" data-toggle="pill"><%= icon("beaker") %> Results</a></li>
		<li id="demographics"><a href="<%= patient_path(@patient) %>"><%= icon("user") %> Demographics</a></li>
		<li id="contact"><a href="<%= patient_contact_path(@patient) %>"><%= icon("phone") %> Contacts</a></li>
		<li id="visits"><a href="<%= patient_visits_path(@patient) %>"><%= icon("globe") %> Visits</a></li>
	</ul>
<% end %>

<%= render template: 'layouts/application' %>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
<%= render template: 'layouts/headers' %>
<body>
	<div class="container">
		<div class="content">
			<div class="span12">
				<%= yield %>
			</div>
		</div><!--/content-->
	</div> <!-- /container -->
</body>
</html>

app/views/layouts/site_chart.html.erb
<% content_for :page_header do %>
<div class="page-header">
  <h1><%= @site.name %> Settings&emsp;<small><%= (@site.abbreviation.blank? ? "none" : @site.abbreviation) %></small></h1>
</div>
<% end %>
<% content_for :sidebar do %>
	<ul class="nav nav-pills nav-stacked">
		<li id="summary"><%= link_icon 'Summary', site_path(@site), 'hospital' %></li>
    <li id="user_groups"><%= link_icon 'User groups', site_user_groups_path(@site), 'group' %>
    <li id="locations"><%= link_icon 'Locations', site_locations_path(@site), 'map-marker' %></li>
	</ul>
<% end %>
<%= render template: 'layouts/application' %>

app/views/layouts/user_chart.html.erb
<% content_for :page_header do %>
<div class="page-header">
  <h1>Settings <small><%= @user.name if current_user != @user %></small></h1>
</div>
<% end %>
<% content_for :sidebar do %>
	<ul class="nav nav-pills nav-stacked">
		<li id="summary"><%= link_icon 'Summary', @user, 'user' %></li>
    <li id="job_description"><%= link_icon 'Job description', job_description_user_path(@user), 'medkit' %>
    <li id="contact"><%= link_icon 'Contacts', user_contact_path(@user), 'phone' %></li>
    <li id="login_record"><%= link_icon 'Login record', login_record_user_path(@user), 'globe' %>
	</ul>
<% end %>
<%= render template: 'layouts/application' %>